### ISSUE TITLE
Documents > Export all data tab separated fails

### ISSUE THREAD

**Issue by pbstudent** [voyanttools/VoyantServer#20]
Status:
Voyant Server 2.5.4
Java jdk-11.0.13_osx-x64_bin.dmg

Export Output:

org.xml.sax.SAXParseException; lineNumber: 111; columnNumber: 35; The prefix "extra.meta" for element "extra.meta:creation-date" is not bound.
net.sf.saxon.trans.XPathException: org.xml.sax.SAXParseException; lineNumber: 111; columnNumber: 35; The prefix "extra.meta" for element "extra.meta:creation-date" is not bound.
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:452)
	at net.sf.saxon.event.Sender.send(Sender.java:170)
	at net.sf.saxon.Controller.transform(Controller.java:1898)
	at org.voyanttools.voyant.XslTransformer.transform(XslTransformer.java:33)
	at org.voyanttools.voyant.Trombone.doRequest(Trombone.java:289)
	at org.voyanttools.voyant.Trombone.doRequest(Trombone.java:146)
	at org.voyanttools.voyant.Trombone.doGet(Trombone.java:80)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:840)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:513)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:539)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.xml.sax.SAXParseException; lineNumber: 111; columnNumber: 35; The prefix "extra.meta" for element "extra.meta:creation-date" is not bound.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:428)
	... 31 more

**Comment by ajmacdonald** [comment]
It's hard to be certain without seeing the sources you're using but this appears to be caused by your XML document(s).
You need to declare the prefixes that your document contains, e.g.
`<root xmlns:extra.meta="http://foo.bar">`

**Comment by pbstudent** [comment]
Hi,

You may observe the error from: https://voyant-tools.org/?corpus=57d833df01af8bf85945a6db20804c6c&panels=cirrus,reader,trends,summary,contexts

**Comment by ajmacdonald** [comment]
The issue appears to be with your `Microsoft Word - HHU_English clean.docx` document.
The export works when I try it with a copy of that corpus that has that document removed: https://voyant-tools.org/trombone?start=0&template=documents2tsv&forTool=documents&tool=corpus.DocumentsMetadata&corpus=aa0381fa2e3543fdb0da8c4f9f9a5773

**Comment by pbstudent** [comment]
Thanks there was a PDF file in the corpus but no DOCX file in the directory. The PDF was derived from a DOCX source.
This will be replaced with a plain text version.
