### ISSUE TITLE
JDTCompiler Error - VoyantServer2_5_4 macos 10.15.7 

### ISSUE THREAD

**Issue by adkiem** [voyanttools/VoyantServer#22]
Unfortunately Voyant stand alone does not work for me. I get the following error messages (copied from the console):

`Using Free AdminPort=34000
Server Starting
2022-06-20 00:03:54.563:INFO::main: Logging initialized @248ms
Jetty Version: 9.3.z-SNAPSHOT
http://*:8888
Jetty starting up ... please wait
2022-06-20 00:03:54.706:INFO:oejs.Server:main: jetty-9.3.z-SNAPSHOT, build timestamp: 2021-10-01T17:51:54+02:00, git hash: 148ea770504ad315b7936c5737e462879680042b
2022-06-20 00:03:55.538:WARN:oeja.AnnotationParser:main: Unknown asm runtime version, assuming version 393216
2022-06-20 00:03:55.554:WARN:oeja.AnnotationParser:qtp933699219-17: org.apache.commons.logging.Log scanned from multiple locations: [jar:file:///Users/Manu_neu/Downloads/PRODUKTIVITAET/VoyantServer2_5_4/_app/WEB-INF/lib/commons-logging-1.2.jar!/org/apache/commons/logging/Log.class, jar:file:///Users/Manu_neu/Downloads/PRODUKTIVITAET/VoyantServer2_5_4/_app/WEB-INF/lib/commons-logging-api-1.1.jar!/org/apache/commons/logging/Log.class]
2022-06-20 00:03:55.566:WARN:oeja.AnnotationParser:qtp933699219-21: org.apache.commons.logging.LogConfigurationException scanned from multiple locations: [jar:file:///Users/Manu_neu/Downloads/PRODUKTIVITAET/VoyantServer2_5_4/_app/WEB-INF/lib/commons-logging-api-1.1.jar!/org/apache/commons/logging/LogConfigurationException.class, jar:file:///Users/Manu_neu/Downloads/PRODUKTIVITAET/VoyantServer2_5_4/_app/WEB-INF/lib/commons-logging-1.2.jar!/org/apache/commons/logging/LogConfigurationException.class]
2022-06-20 00:03:57.237:INFO:oeja.AnnotationConfiguration:main: Scanning elapsed time=1695ms
2022-06-20 00:03:57.403:WARN:oejs.SecurityHandler:main: ServletContext@o.e.j.w.WebAppContext@42a15bdc{/,file:///Users/Manu_neu/Downloads/PRODUKTIVITAET/VoyantServer2_5_4/_app/,STARTING} has uncovered http methods for path: /
2022-06-20 00:03:57.460:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@42a15bdc{/,file:///Users/Manu_neu/Downloads/PRODUKTIVITAET/VoyantServer2_5_4/_app/,AVAILABLE}
2022-06-20 00:03:57.479:INFO:oejs.AbstractConnector:main: Started ServerConnector@4f6f416f{HTTP/1.1,[http/1.1]}{0.0.0.0:8888}
... Jetty has started.
2022-06-20 00:03:57.480:INFO:oejs.Server:main: Started @3176ms
2022-06-20 00:03:58.427:WARN:oajc.JDTCompiler:qtp933699219-19: Compilation error
org.eclipse.jdt.internal.compiler.classfmt.ClassFormatException
	at org.eclipse.jdt.internal.compiler.classfmt.ClassFileReader.<init>(ClassFileReader.java:393)
	at org.apache.jasper.compiler.JDTCompiler$1.findType(JDTCompiler.java:210)
	at org.apache.jasper.compiler.JDTCompiler$1.findType(JDTCompiler.java:182)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:160)
	at org.eclipse.jdt.internal.compiler.lookup.PackageBinding.getType(PackageBinding.java:145)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.findType(Scope.java:2037)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getTypeOrPackage(Scope.java:3349)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getBinding(Scope.java:2303)
	at org.eclipse.jdt.internal.compiler.ast.SingleNameReference.resolveType(SingleNameReference.java:985)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.resolveType(MessageSend.java:605)
	at org.eclipse.jdt.internal.compiler.ast.EqualExpression.resolveType(EqualExpression.java:827)
	at org.eclipse.jdt.internal.compiler.ast.Expression.resolveTypeExpecting(Expression.java:1050)
	at org.eclipse.jdt.internal.compiler.ast.ConditionalExpression.resolveType(ConditionalExpression.java:458)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.resolveType(MessageSend.java:651)
	at org.eclipse.jdt.internal.compiler.ast.Expression.resolve(Expression.java:1020)
	at org.eclipse.jdt.internal.compiler.ast.Block.resolveUsing(Block.java:127)
	at org.eclipse.jdt.internal.compiler.ast.TryStatement.resolve(TryStatement.java:1085)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolveStatements(AbstractMethodDeclaration.java:619)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.resolveStatements(MethodDeclaration.java:299)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolve(AbstractMethodDeclaration.java:529)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1207)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1320)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.resolve(CompilationUnitDeclaration.java:590)
	at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:770)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:470)
	at org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:447)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:361)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:336)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:323)
	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:585)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:363)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:513)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:199)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:74)
	at org.eclipse.jetty.servlet.DefaultServlet.sendWelcome(DefaultServlet.java:604)
	at org.eclipse.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:489)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:840)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:513)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:539)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.base/java.lang.Thread.run(Thread.java:833)
2022-06-20 00:03:58.491:WARN:oejs.ServletHandler:qtp933699219-19: 
org.apache.jasper.JasperException: Unable to compile class for JSP: ||An error occurred at line: 52 in the jsp file: /index.jsp|System cannot be resolved|49: ??config: {|50: ???baseUrl: '<%= org.voyanttools.voyant.Voyant.getBaseUrlString(request) %>',|51: ???version: '<%= application.getInitParameter("version") %>',|52: ???openMenu: '<%= System.getProperty("org.voyanttools.voyant.openmenu")==null ? "" : System.getProperty("org.voyanttools.voyant.openmenu") %>',|53: ???allowInput: '<%= System.getProperty("org.voyanttools.server.allowinput")==null ? "" : System.getProperty("org.voyanttools.server.allowinput") %>',|54: ???allowDownload: '<%= System.getProperty("org.voyanttools.server.allowdownload")==null ? "" : System.getProperty("org.voyanttools.server.allowdownload") %>'|55: ??},|||An error occurred at line: 52 in the jsp file: /index.jsp|System cannot be resolved|49: ??config: {|50: ???baseUrl: '<%= org.voyanttools.voyant.Voyant.getBaseUrlString(request) %>',|51: ???version: '<%= application.getInitParameter("version") %>',|52: ???openMenu: '<%= System.getProperty("org.voyanttools.voyant.openmenu")==null ? "" : System.getProperty("org.voyanttools.voyant.openmenu") %>',|53: ???allowInput: '<%= System.getProperty("org.voyanttools.server.allowinput")==null ? "" : System.getProperty("org.voyanttools.server.allowinput") %>',|54: ???allowDownload: '<%= System.getProperty("org.voyanttools.server.allowdownload")==null ? "" : System.getProperty("org.voyanttools.server.allowdownload") %>'|55: ??},|||An error occurred at line: 53 in the jsp file: /index.jsp|System cannot be resolved|50: ???baseUrl: '<%= org.voyanttools.voyant.Voyant.getBaseUrlString(request) %>',|51: ???version: '<%= application.getInitParameter("version") %>',|52: ???openMenu: '<%= System.getProperty("org.voyanttools.voyant.openmenu")==null ? "" : System.getProperty("org.voyanttools.voyant.openmenu") %>',|53: ???allowInput: '<%= System.getProperty("org.voyanttools.server.allowinput")==null ? "" : System.getProperty("org.voyanttools.server.allowinput") %>',|54: ???allowDownload: '<%= System.getProperty("org.voyanttools.server.allowdownload")==null ? "" : System.getProperty("org.voyanttools.server.allowdownload") %>'|55: ??},|56: ??launch: function() {|||An error occurred at line: 53 in the jsp file: /index.jsp|System cannot be resolved|50: ???baseUrl: '<%= org.voyanttools.voyant.Voyant.getBaseUrlString(request) %>',|51: ???version: '<%= application.getInitParameter("version") %>',|52: ???openMenu: '<%= System.getProperty("org.voyanttools.voyant.openmenu")==null ? "" : System.getProperty("org.voyanttools.voyant.openmenu") %>',|53: ???allowInput: '<%= System.getProperty("org.voyanttools.server.allowinput")==null ? "" : System.getProperty("org.voyanttools.server.allowinput") %>',|54: ???allowDownload: '<%= System.getProperty("org.voyanttools.server.allowdownload")==null ? "" : System.getProperty("org.voyanttools.server.allowdownload") %>'|55: ??},|56: ??launch: function() {|||An error occurred at line: 54 in the jsp file: /index.jsp|System cannot be resolved|51: ???version: '<%= application.getInitParameter("version") %>',|52: ???openMenu: '<%= System.getProperty("org.voyanttools.voyant.openmenu")==null ? "" : System.getProperty("org.voyanttools.voyant.openmenu") %>',|53: ???allowInput: '<%= System.getProperty("org.voyanttools.server.allowinput")==null ? "" : System.getProperty("org.voyanttools.server.allowinput") %>',|54: ???allowDownload: '<%= System.getProperty("org.voyanttools.server.allowdownload")==null ? "" : System.getProperty("org.voyanttools.server.allowdownload") %>'|55: ??},|56: ??launch: function() {|57: ??   ?var me = this;|||An error occurred at line: 54 in the jsp file: /index.jsp|System cannot be resolved|51: ???version: '<%= application.getInitParameter("version") %>',|52: ???openMenu: '<%= System.getProperty("org.voyanttools.voyant.openmenu")==null ? "" : System.getProperty("org.voyanttools.voyant.openmenu") %>',|53: ???allowInput: '<%= System.getProperty("org.voyanttools.server.allowinput")==null ? "" : System.getProperty("org.voyanttools.server.allowinput") %>',|54: ???allowDownload: '<%= System.getProperty("org.voyanttools.server.allowdownload")==null ? "" : System.getProperty("org.voyanttools.server.allowdownload") %>'|55: ??},|56: ??launch: function() {|57: ??   ?var me = this;|||Stacktrace:
	at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:102)
	at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:198)
	at org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:457)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:361)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:336)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:323)
	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:585)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:363)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:513)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:199)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:74)
	at org.eclipse.jetty.servlet.DefaultServlet.sendWelcome(DefaultServlet.java:604)
	at org.eclipse.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:489)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:840)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:513)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:539)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.base/java.lang.Thread.run(Thread.java:833)`

Any other macos users getting the same error?

**Comment by ajmacdonald** [comment]
Hello @adkiem,
Can you please tell me which version of Java you have installed?

**Comment by adkiem** [comment]
Hello @ajmacdonald,

thanks for your reply! it is java 17.0.3.1

**Comment by ajmacdonald** [comment]
Java 17 isn't supported so that may be the problem. Please try it with Java 11.
See my response to a similar issue here: https://github.com/voyanttools/VoyantServer/issues/23#issuecomment-1170397780
