### ISSUE TITLE
Error 500 Unable to compile class for JSP

### ISSUE THREAD

**Issue by afendi** [voyanttools/VoyantServer#5]
I'm new to Voyant, but everything is set up with default values (nothing changed in the server settings). Not sure what could be the problem.

HTTP ERROR 500
Problem accessing /. Reason:

    Server Error
Caused by:
org.apache.jasper.JasperException: Unable to compile class for JSP: 

An error occurred at line: 52 in the jsp file: /index.jsp
System cannot be resolved
49: 		config: {
50: 			baseUrl: '<%= org.voyanttools.voyant.Voyant.getBaseUrlString(request) %>',
51: 			version: '<%= application.getInitParameter("version") %>',
52: 			openMenu: '<%= System.getProperty("org.voyanttools.voyant.openmenu")==null ? "" : System.getProperty("org.voyanttools.voyant.openmenu") %>',
53: 			allowInput: '<%= System.getProperty("org.voyanttools.server.allowinput")==null ? "" : System.getProperty("org.voyanttools.server.allowinput") %>',
54: 			allowDownload: '<%= System.getProperty("org.voyanttools.server.allowdownload")==null ? "" : System.getProperty("org.voyanttools.server.allowdownload") %>'
55: 		},

An error occurred at line: 52 in the jsp file: /index.jsp
System cannot be resolved
49: 		config: {
50: 			baseUrl: '<%= org.voyanttools.voyant.Voyant.getBaseUrlString(request) %>',
51: 			version: '<%= application.getInitParameter("version") %>',
52: 			openMenu: '<%= System.getProperty("org.voyanttools.voyant.openmenu")==null ? "" : System.getProperty("org.voyanttools.voyant.openmenu") %>',
53: 			allowInput: '<%= System.getProperty("org.voyanttools.server.allowinput")==null ? "" : System.getProperty("org.voyanttools.server.allowinput") %>',
54: 			allowDownload: '<%= System.getProperty("org.voyanttools.server.allowdownload")==null ? "" : System.getProperty("org.voyanttools.server.allowdownload") %>'
55: 		},

An error occurred at line: 53 in the jsp file: /index.jsp
System cannot be resolved
50: 			baseUrl: '<%= org.voyanttools.voyant.Voyant.getBaseUrlString(request) %>',
51: 			version: '<%= application.getInitParameter("version") %>',
52: 			openMenu: '<%= System.getProperty("org.voyanttools.voyant.openmenu")==null ? "" : System.getProperty("org.voyanttools.voyant.openmenu") %>',
53: 			allowInput: '<%= System.getProperty("org.voyanttools.server.allowinput")==null ? "" : System.getProperty("org.voyanttools.server.allowinput") %>',
54: 			allowDownload: '<%= System.getProperty("org.voyanttools.server.allowdownload")==null ? "" : System.getProperty("org.voyanttools.server.allowdownload") %>'
55: 		},
56: 		launch: function() {

An error occurred at line: 53 in the jsp file: /index.jsp
System cannot be resolved
50: 			baseUrl: '<%= org.voyanttools.voyant.Voyant.getBaseUrlString(request) %>',
51: 			version: '<%= application.getInitParameter("version") %>',
52: 			openMenu: '<%= System.getProperty("org.voyanttools.voyant.openmenu")==null ? "" : System.getProperty("org.voyanttools.voyant.openmenu") %>',
53: 			allowInput: '<%= System.getProperty("org.voyanttools.server.allowinput")==null ? "" : System.getProperty("org.voyanttools.server.allowinput") %>',
54: 			allowDownload: '<%= System.getProperty("org.voyanttools.server.allowdownload")==null ? "" : System.getProperty("org.voyanttools.server.allowdownload") %>'
55: 		},
56: 		launch: function() {

An error occurred at line: 54 in the jsp file: /index.jsp
System cannot be resolved
51: 			version: '<%= application.getInitParameter("version") %>',
52: 			openMenu: '<%= System.getProperty("org.voyanttools.voyant.openmenu")==null ? "" : System.getProperty("org.voyanttools.voyant.openmenu") %>',
53: 			allowInput: '<%= System.getProperty("org.voyanttools.server.allowinput")==null ? "" : System.getProperty("org.voyanttools.server.allowinput") %>',
54: 			allowDownload: '<%= System.getProperty("org.voyanttools.server.allowdownload")==null ? "" : System.getProperty("org.voyanttools.server.allowdownload") %>'
55: 		},
56: 		launch: function() {
57: 		   	var me = this;

An error occurred at line: 54 in the jsp file: /index.jsp
System cannot be resolved
51: 			version: '<%= application.getInitParameter("version") %>',
52: 			openMenu: '<%= System.getProperty("org.voyanttools.voyant.openmenu")==null ? "" : System.getProperty("org.voyanttools.voyant.openmenu") %>',
53: 			allowInput: '<%= System.getProperty("org.voyanttools.server.allowinput")==null ? "" : System.getProperty("org.voyanttools.server.allowinput") %>',
54: 			allowDownload: '<%= System.getProperty("org.voyanttools.server.allowdownload")==null ? "" : System.getProperty("org.voyanttools.server.allowdownload") %>'
55: 		},
56: 		launch: function() {
57: 		   	var me = this;

Stacktrace:
	at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:102)
	at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:198)
	at org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:457)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:361)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:336)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:323)
	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:585)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:363)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:513)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:199)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:74)
	at org.eclipse.jetty.servlet.DefaultServlet.sendWelcome(DefaultServlet.java:604)
	at org.eclipse.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:489)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:840)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:513)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:539)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by ajmacdonald** [comment]
Hello @afendi 
You are trying to run the VoyantServer.jar file?
Can you please tell me what version of Java you have installed?

**Comment by afendi** [comment]
Yes, trying to run VoyantServer.jar.
The Java version I have is 17.0.1

**Comment by ajmacdonald** [comment]
Unfortunately VoyantServer does not currently work with newer versions of Java. You'll need to download version 11 and run the jar using that.
